name = "Marconi"
uuid = "bbe32c30-8a1d-11e9-18de-655e918680e9"
authors = ["kiranshila <kiranshila@mail.usf.edu>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1"

[extras]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "PGFPlotsX", "Coverage"]
